---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/admin"
    schedule:
      interval: "weekly"
  - package-ecosystem: composer
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/miniapp"
    schedule:
      interval: "weekly"
